#cloud-config
package_update: true
packages:
  - docker.io
runcmd:
  - cd /root
  - docker run --detach --hostname gitlab.proyecto23.es --publish 80:80 --publish 20:22 --name gitlab --restart always --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce:latest
